config/routes.rb
Rails.application.routes.draw do
  # --- Public（エンドユーザー） ---
  devise_for :users, controllers: {
    registrations: 'public/users/registrations',
    sessions:      'public/users/sessions'
  }

  # --- Admin 認証（モデルは AdminUser、URL は /admin/*）---
  devise_for :admin,
  class_name: 'AdminUser',
  path: 'admin',
  skip: [:registrations, :passwords], 
  controllers: {sessions: 'admin/admin_users/sessions' }

  scope module: :public do
    root 'homes#top'

    resources :users, only: [:show, :edit, :update] do
      member do
        patch :promote_to_family_admin
        patch :demote_from_family_admin
      end
        patch :withdraw, on: :member
    end

    resource :family, only: [:show, :edit, :update] do
      resources :profiles
    end

    resources :posts do
      resources :comments, only: [:create, :edit, :update, :destroy]  
    end
  end


  
  # --- Admin 画面 ---
  namespace :admin do
    root 'dashboard#top'
    resources :users, only: [:index, :show, :update, :destroy] do
      member do
        patch :promote_family_admin   # 家族管理者にする
        patch :demote_family_admin    # 一般ユーザーに戻す
      end
    end
    resources :posts,    only: [:index, :show, :edit, :update, :destroy]
    resources :profiles, only: [:index, :destroy]
    resources :comments, only: [:index, :destroy]
    resources :tags,     only: [:index, :edit, :update, :destroy, :new, :create] do
      patch :restore, on: :member
    end
  end
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < Admin::ApplicationController
  def top
    @users_count    = User.count
    @posts_count    = Post.count
    @profiles_count = Profile.count
  end
end

app/views/admin/dashboard/index.html.erb
<h1 class="mb-3">Admin Dashboard</h1>
<ul>
  <li>Users: <%= @users_count %></li>
  <li>Posts: <%= @posts_count %></li>
  <li>Profiles: <%= @profiles_count %></li>
</ul>

app/views/admin/dashboard/top.html.erb
<div class="container mt-4">
  <h1>管理者ホーム</h1>
  <p><%= current_admin.email %> としてログイン中です。</p>

  <ul class="mt-3">
    <li><%= link_to "ユーザー管理", admin_users_path, class: "btn btn-outline-primary mb-2" %></li>
    <li><%= link_to "投稿管理", admin_posts_path, class: "btn btn-outline-primary mb-2" %></li>
    <li><%= link_to "コメント管理", admin_comments_path, class: "btn btn-outline-primary mb-2" %></li>
    <li><%= link_to "性格タグ管理", admin_tags_path, class: "btn btn-outline-primary mb-2" %>
  </ul>
</div>